version: "3.9"

services:
  app: #name of the service
    build:
      context: .
      args:
        - DEV=true
    ports: #8000 on local to 8000 on cotainer
      - "8000:8000"
    volumes: #mapping the volumes in local to container, for autoatic syncing
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"